import swaggerAutogen from "swagger-autogen";
import dotEnv from "dotenv";

dotEnv.config();
const PORT = process.env.PORT || 3000;
const host = process.env.HOST || "localhost";

const doc = {
  info: {
    version: "1.0.0",
    title: "Rental Booking",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `${host}:${PORT}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Auth",
      description: "Authentication routes",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "any description...",
    },
  },
  definitions: {
    Parents: {
      father: "Simon Doe",
      mother: "Marie Doe",
    },
    User: {
      name: "Jhon Doe",
      age: 29,
      parents: {
        $ref: "#/definitions/Parents",
      },
      diplomas: [
        {
          school: "XYZ University",
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: "XYZ Company",
          },
        },
      ],
    },
    AddUser: {
      $name: "Jhon Doe",
      $age: 29,
      about: "",
    },
  },
};


const outputFile = "../swagger-output.json";
const endpointsFiles = ["./app"];

export default swaggerAutogen()(outputFile, endpointsFiles, doc)